### ISSUE TITLE
Support for context managing and scandir.close()

### ISSUE THREAD

**Issue by h5rdly** [benhoyt/scandir#69] opened 2017-01-03 15:27 UTC
Hi,

First, thank you for this library, super useful.

I saw that Python 3.6 introduced context managing and the close() function to save resources. Would it be possible to add them to the autonomous scandir module as well? I use scandir rigorousy so that would be sweet :)

**Comment by benhoyt** [comment] 2017-01-03 16:14
Hi @h5rdly -- good call! This is a duplicate of https://github.com/benhoyt/scandir/issues/60 so I'm closing this one. Feel free to comment over there. I haven't been working on scandir for a while, so if you've done C+Python development you'd be most welcome to submit a patch to make this happen faster. Be aware it won't be trivial though: it will involve C code, Python code (for the pure Python fallback), unit tests, and documentation.

**Closed by benhoyt** 2017-01-03 16:14 UTC
