### ISSUE TITLE
test_stat fails in Windows.

### ISSUE THREAD

**Issue by dumol** [benhoyt/scandir#77] opened 2017-03-02 17:47 UTC
This happens with scandir 1.5 and Python 2.7.11 in a Windows XP x86 build slave running MINGW32. This is the only Windows machine on which we test our python package (publicly available at https://github.com/chevah/python-package). This particular test passes our Linux and Unix build slaves.
```
======================================================================
FAIL: test_stat (test_scandir.TestScandirPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\buildslave\chevah\bs\python-package-win-xp-dev\build\python-modules\python-scandir-1.5\test\test_scandir.py", line 136, in test_stat
    self.assertEqual(os_stat.st_mtime, scandir_stat.st_mtime)
AssertionError: 1488384798.542208 != 1488384798.5422077

----------------------------------------------------------------------
Ran 23 tests in 0.020s

FAILED (failures=1, skipped=3)
```
Another example, for variety:
```
======================================================================
FAIL: test_stat (test_scandir.TestScandirPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\buildslave\chevah\bs\python-package-win-xp-dev\build\python-modules\python-scandir-1.5\test\test_scandir.py", line 136, in test_stat
    self.assertEqual(os_stat.st_mtime, scandir_stat.st_mtime)
AssertionError: 1488389708.2920816 != 1488389708.2920818
```

**Comment by benhoyt** [comment] 2017-03-02 17:58
Thanks for the report. Yeah, I noticed this the other day too, though I think it was on a Linux-based system. Not sure whether it's a regression in scandir (I don't think so, as nothing's changed), or an improvement/fix in os.stat() resolution, or something else. I'll dig in at some point.

In the meantime, if you can help with debugging / finding the root cause, that would be much appreciated.

**Comment by dumol** [comment] 2017-03-02 18:29
This particular test doesn't fail on our Linux slaves, but they have problems with the Unicode strings and lots of other test subsequently fail, will report this in a separate ticket. Can't speak about regressions, as we are currently integrating the `scandir` module for the first time.

For the moment we don't have resources to thoroughly debug this issue, I am currently implementing a simple workaround: rounding the results for `mtime` and `ctime` (they both fail intermittently on Windows).

**Comment by adiroiban** [comment] 2017-03-03 07:30
I don't think there is a bug in the code... but the assertion is not right.

The way the test stat is written right now https://github.com/benhoyt/scandir/blob/master/test/test_scandir.py#L130 this failure is expected.

It does

```
1>            os_stat = os.stat(os.path.join(TEST_PATH, entry.name))
2>            scandir_stat = entry.stat()
```

there is no guarantee that between call 1 and call 2 the OS will not switch the process context and execute another process... so by the time the OS will switch back to the Python test process and execute call 2 there might be a milisecond time distance.

I have executed the test_stat  on my computer and it always pass.
Is very hard to reproduce it.

Here, the difference is of 200 nano seconds ... and I think that the test should use a delta of 1 micro second assertAlmoustEqual(delta=0.000001)

-------------

@benhoyt It this the same code which was included in Python 3? I could not found this test upstream.

**Comment by benhoyt** [comment] 2017-09-29 12:55
I still don't understand why this is happening. @adiroiban says above that there is no guarantee that the times will be the same between the two calls. But this is testing the mtime (time last modified) and ctime (time created), both of which should be 100% constant after the file is created.

So there's something weird going on here. To get the tests passing for now, I've just added a large delta in the test (sometimes it's tens of milliseconds).

But I'll leave this open so we can find the underlying issue at some point.

**Comment by adiroiban** [comment] 2017-09-29 13:09
@benhoyt Thanks for the follow up.

I have no idea what was in my head in March... definitely not much :)

Yes the behaviour is very strange.

Maybe it can help if there are unit tests for os.stat itself, compared with the low level API calls used by scandir.

**Comment by benhoyt** [comment] 2021-09-25 05:50
Going to close this seeing the failure is not happening anymore due to the larger delta.

**Closed by benhoyt** 2021-09-25 05:50 UTC
